# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: mortgage-client
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      
server:
  port: 8787

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false
    
      
